class DnModel {
  final String name;
  final String specialization;
  final String hospital;
  final int rating;
  final String? image;

  DnModel({
    required this.name,
    required this.specialization,
    required this.hospital,
    required this.rating,
    required this.image,
  });
}

final List<DnModel> fakedatadoctor = [
  DnModel(
    name: "Dr. John Smith",
    specialization: "Cardiologist",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  ),
  DnModel(
    name: "Dr. Emily Johnson",
    specialization: "Neurologist",
    hospital: "Cleveland Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  ),
  DnModel(
    name: "Dr. Michael Brown",
    specialization: "Orthopedic Surgeon",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/65.jpg",
  ),
  DnModel(
    name: "Dr. Sophia Martinez",
    specialization: "Pediatrician",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/68.jpg",
  ),
  DnModel(
    name: "Dr. Daniel Wilson",
    specialization: "Dermatologist",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/75.jpg",
  ),
  DnModel(
    name: "Dr. Olivia Taylor",
    specialization: "Oncologist",
    hospital: "MD Anderson Cancer Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  ),
  DnModel(
    name: "Dr. William Davis",
    specialization: "Psychiatrist",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  ),
  DnModel(
    name: "Dr. Isabella Garcia",
    specialization: "Gynecologist",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/30.jpg",
  ),
  DnModel(
    name: "Dr. James Anderson",
    specialization: "Endocrinologist",
    hospital: "Brigham and Women's Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/40.jpg",
  ),
  DnModel(
    name: "Dr. Mia Rodriguez",
    specialization: "Family Medicine",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/50.jpg",
  ),
  DnModel(
    name: "Dr. Ethan Thomas",
    specialization: "Radiologist",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/51.jpg",
  ),
  DnModel(
    name: "Dr. Charlotte Lee",
    specialization: "Rheumatologist",
    hospital: "Cleveland Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/52.jpg",
  ),
  DnModel(
    name: "Dr. Benjamin Harris",
    specialization: "Ophthalmologist",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/53.jpg",
  ),
  DnModel(
    name: "Dr. Amelia Clark",
    specialization: "Pathologist",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/54.jpg",
  ),
  DnModel(
    name: "Dr. Alexander Lewis",
    specialization: "Urologist",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/55.jpg",
  ),
  DnModel(
    name: "Dr. Harper Walker",
    specialization: "Allergist",
    hospital: "MD Anderson Cancer Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/56.jpg",
  ),
  DnModel(
    name: "Dr. Daniel Hall",
    specialization: "Gastroenterologist",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/57.jpg",
  ),
  DnModel(
    name: "Dr. Evelyn Allen",
    specialization: "Nephrologist",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/58.jpg",
  ),
  DnModel(
    name: "Dr. Lucas Young",
    specialization: "Hematologist",
    hospital: "Brigham and Women's Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/59.jpg",
  ),
  DnModel(
    name: "Dr. Abigail King",
    specialization: "Plastic Surgeon",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/60.jpg",
  ),
  DnModel(
    name: "Dr. Henry Wright",
    specialization: "Pulmonologist",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/61.jpg",
  ),
  DnModel(
    name: "Dr. Ella Scott",
    specialization: "Infectious Disease",
    hospital: "Cleveland Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/62.jpg",
  ),
  DnModel(
    name: "Dr. Matthew Green",
    specialization: "General Surgeon",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/63.jpg",
  ),
  DnModel(
    name: "Dr. Lily Adams",
    specialization: "Anesthesiologist",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/64.jpg",
  ),
  DnModel(
    name: "Dr. David Baker",
    specialization: "Occupational Medicine",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/66.jpg",
  ),
  DnModel(
    name: "Dr. Grace Nelson",
    specialization: "Emergency Medicine",
    hospital: "MD Anderson Cancer Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/67.jpg",
  ),
  DnModel(
    name: "Dr. Christopher Hill",
    specialization: "Sports Medicine",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/69.jpg",
  ),
  DnModel(
    name: "Dr. Aria Rivera",
    specialization: "Internal Medicine",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/70.jpg",
  ),
  DnModel(
    name: "Dr. Andrew Campbell",
    specialization: "Vascular Surgeon",
    hospital: "Brigham and Women's Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/71.jpg",
  ),
  DnModel(
    name: "Dr. Scarlett Mitchell",
    specialization: "Geriatrician",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/72.jpg",
  ),
  DnModel(
    name: "Dr. Joseph Parker",
    specialization: "Palliative Care",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/73.jpg",
  ),
  DnModel(
    name: "Dr. Victoria Evans",
    specialization: "Immunologist",
    hospital: "Cleveland Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/74.jpg",
  ),
  DnModel(
    name: "Dr. Samuel Turner",
    specialization: "Geneticist",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/76.jpg",
  ),
  DnModel(
    name: "Dr. Zoe Carter",
    specialization: "Clinical Pharmacologist",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/77.jpg",
  ),
  DnModel(
    name: "Dr. Jack Morris",
    specialization: "Rehabilitation Medicine",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/78.jpg",
  ),
  DnModel(
    name: "Dr. Nora Bell",
    specialization: "Pain Management",
    hospital: "MD Anderson Cancer Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/79.jpg",
  ),
  DnModel(
    name: "Dr. Anthony Rivera",
    specialization: "Nuclear Medicine",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/80.jpg",
  ),
  DnModel(
    name: "Dr. Layla Perez",
    specialization: "Public Health",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/81.jpg",
  ),
  DnModel(
    name: "Dr. Ryan Kelly",
    specialization: "Forensic Pathology",
    hospital: "Brigham and Women's Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/82.jpg",
  ),
  DnModel(
    name: "Dr. Hannah Foster",
    specialization: "Critical Care",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/83.jpg",
  ),
  DnModel(
    name: "Dr. Jason Gray",
    specialization: "Thoracic Surgeon",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/84.jpg",
  ),
  DnModel(
    name: "Dr. Chloe Ward",
    specialization: "Sleep Medicine",
    hospital: "Cleveland Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/85.jpg",
  ),
  DnModel(
    name: "Dr. Nathan Murphy",
    specialization: "Otolaryngologist",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/86.jpg",
  ),
  DnModel(
    name: "Dr. Zoe Ramirez",
    specialization: "Medical Genetics",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/87.jpg",
  ),
  DnModel(
    name: "Dr. Dylan Hughes",
    specialization: "Toxicologist",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/88.jpg",
  ),
  DnModel(
    name: "Dr. Sofia Brooks",
    specialization: "Clinical Neurophysiology",
    hospital: "MD Anderson Cancer Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/women/89.jpg",
  ),
  DnModel(
    name: "Dr. Gabriel Price",
    specialization: "Emergency Psychiatry",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/men/90.jpg",
  ),
];
final List<DnModel> fakedatanurse = [
  DnModel(
    name: "Nurse Emma Johnson",
    specialization: "ICU Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/11.jpg",
  ),
  DnModel(
    name: "Nurse Liam Smith",
    specialization: "Pediatric Nurse",
    hospital: "Cleveland Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  ),
  DnModel(
    name: "Nurse Ava Williams",
    specialization: "Surgical Nurse",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/13.jpg",
  ),
  DnModel(
    name: "Nurse Noah Brown",
    specialization: "ER Nurse",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/14.jpg",
  ),
  DnModel(
    name: "Nurse Isabella Davis",
    specialization: "Oncology Nurse",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  ),
  DnModel(
    name: "Nurse Mason Miller",
    specialization: "Psychiatric Nurse",
    hospital: "MD Anderson Cancer Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/16.jpg",
  ),
  DnModel(
    name: "Nurse Sophia Wilson",
    specialization: "Community Health Nurse",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/17.jpg",
  ),
  DnModel(
    name: "Nurse James Moore",
    specialization: "Cardiac Nurse",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  ),
  DnModel(
    name: "Nurse Mia Taylor",
    specialization: "Neonatal Nurse",
    hospital: "Brigham and Women's Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  ),
  DnModel(
    name: "Nurse Elijah Anderson",
    specialization: "Geriatric Nurse",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  ),
  DnModel(
    name: "Nurse Amelia Thomas",
    specialization: "Orthopedic Nurse",
    hospital: "Cleveland Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/21.jpg",
  ),
  DnModel(
    name: "Nurse Lucas Jackson",
    specialization: "Trauma Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  ),
  DnModel(
    name: "Nurse Harper White",
    specialization: "Dialysis Nurse",
    hospital: "Mount Sinai Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/23.jpg",
  ),
  DnModel(
    name: "Nurse Benjamin Harris",
    specialization: "Anesthesia Nurse",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
  ),
  DnModel(
    name: "Nurse Evelyn Martin",
    specialization: "Psychiatric Nurse",
    hospital: "UCLA Medical Center, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  ),
  DnModel(
    name: "Nurse Henry Thompson",
    specialization: "ER Nurse",
    hospital: "Stanford Health Care, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/26.jpg",
  ),
  DnModel(
    name: "Nurse Charlotte Garcia",
    specialization: "ICU Nurse",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/27.jpg",
  ),
  DnModel(
    name: "Nurse Alexander Martinez",
    specialization: "Pediatric Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/28.jpg",
  ),
  DnModel(
    name: "Nurse Abigail Robinson",
    specialization: "Surgical Nurse",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/29.jpg",
  ),
  DnModel(
    name: "Nurse William Clark",
    specialization: "Geriatric Nurse",
    hospital: "MD Anderson Cancer Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/30.jpg",
  ),
  DnModel(
    name: "Nurse Ella Rodriguez",
    specialization: "Neonatal Nurse",
    hospital: "Cleveland Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/31.jpg",
  ),
  DnModel(
    name: "Nurse Daniel Lewis",
    specialization: "Cardiac Nurse",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  ),
  DnModel(
    name: "Nurse Aria Lee",
    specialization: "Oncology Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/33.jpg",
  ),
  DnModel(
    name: "Nurse Matthew Walker",
    specialization: "Community Health Nurse",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/34.jpg",
  ),
  DnModel(
    name: "Nurse Scarlett Hall",
    specialization: "ER Nurse",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/35.jpg",
  ),
  DnModel(
    name: "Nurse Joseph Allen",
    specialization: "Orthopedic Nurse",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/36.jpg",
  ),
  DnModel(
    name: "Nurse Grace Young",
    specialization: "Trauma Nurse",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/37.jpg",
  ),
  DnModel(
    name: "Nurse David King",
    specialization: "Psychiatric Nurse",
    hospital: "Massachusetts General Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/38.jpg",
  ),
  DnModel(
    name: "Nurse Lily Wright",
    specialization: "Dialysis Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/39.jpg",
  ),
  DnModel(
    name: "Nurse Samuel Scott",
    specialization: "Anesthesia Nurse",
    hospital: "Cleveland Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/40.jpg",
  ),
  DnModel(
    name: "Nurse Chloe Green",
    specialization: "Oncology Nurse",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/41.jpg",
  ),
  DnModel(
    name: "Nurse Jackson Adams",
    specialization: "Pediatric Nurse",
    hospital: "Stanford Health Care, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/42.jpg",
  ),
  DnModel(
    name: "Nurse Victoria Baker",
    specialization: "ICU Nurse",
    hospital: "Mount Sinai Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/43.jpg",
  ),
  DnModel(
    name: "Nurse Michael Gonzalez",
    specialization: "ER Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/44.jpg",
  ),
  DnModel(
    name: "Nurse Zoe Nelson",
    specialization: "Community Health Nurse",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/45.jpg",
  ),
  DnModel(
    name: "Nurse Ethan Carter",
    specialization: "Geriatric Nurse",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/46.jpg",
  ),
  DnModel(
    name: "Nurse Hannah Mitchell",
    specialization: "Surgical Nurse",
    hospital: "Massachusetts General Hospital, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/47.jpg",
  ),
  DnModel(
    name: "Nurse Logan Perez",
    specialization: "Cardiac Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/48.jpg",
  ),
  DnModel(
    name: "Nurse Ella Roberts",
    specialization: "Neonatal Nurse",
    hospital: "Cleveland Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/49.jpg",
  ),
  DnModel(
    name: "Nurse Aiden Turner",
    specialization: "Orthopedic Nurse",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/50.jpg",
  ),
  DnModel(
    name: "Nurse Harper Phillips",
    specialization: "ICU Nurse",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/51.jpg",
  ),
  DnModel(
    name: "Nurse Carter Campbell",
    specialization: "ER Nurse",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/52.jpg",
  ),
  DnModel(
    name: "Nurse Scarlett Parker",
    specialization: "Oncology Nurse",
    hospital: "Cedars-Sinai Medical Center, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/53.jpg",
  ),
  DnModel(
    name: "Nurse Wyatt Evans",
    specialization: "Trauma Nurse",
    hospital: "UCLA Medical Center, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/54.jpg",
  ),
  DnModel(
    name: "Nurse Layla Edwards",
    specialization: "Pediatric Nurse",
    hospital: "Mayo Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
  ),
  DnModel(
    name: "Nurse Gabriel Collins",
    specialization: "Dialysis Nurse",
    hospital: "Massachusetts General Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/56.jpg",
  ),
  DnModel(
    name: "Nurse Avery Stewart",
    specialization: "Psychiatric Nurse",
    hospital: "Cleveland Clinic, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/57.jpg",
  ),
  DnModel(
    name: "Nurse Julian Sanchez",
    specialization: "Anesthesia Nurse",
    hospital: "Johns Hopkins Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/58.jpg",
  ),
  DnModel(
    name: "Nurse Stella Morris",
    specialization: "Community Health Nurse",
    hospital: "Stanford Health Care, USA",
    rating: 5,
    image: "https://randomuser.me/api/portraits/women/59.jpg",
  ),
  DnModel(
    name: "Nurse Isaac Rogers",
    specialization: "Cardiac Nurse",
    hospital: "Mount Sinai Hospital, USA",
    rating: 4,
    image: "https://randomuser.me/api/portraits/men/60.jpg",
  ),
];
